package htsjdk.samtools;

import htsjdk.samtools.BAMFileWriter;

import java.io.File;
import java.io.OutputStream;

/**
 * TODO: Insert description here. (generated by tjredekopp)
 */
public class BAMBlockWriter extends BAMFileWriter {
  public BAMBlockWriter(final OutputStream os, final File file, final boolean writeEndBlock) {
    super(os, file);
    this.blockCompressedOutputStream.setWriteEndBlock(writeEndBlock);
  }
}
